-- 1. Custom Types
create type public.user_role as enum ('admin', 'volunteer', 'merchant', 'victim');
create type public.transaction_type as enum ('AID_DISBURSEMENT', 'PURCHASE', 'FUNDS_RETURN');

-- 2. Profiles Table
create table public.profiles (
  id uuid not null primary key default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  full_name text,
  role user_role not null default 'victim'::user_role
);
comment on table public.profiles is 'Stores user profile information.';

-- 3. Wallets Table
create table public.wallets (
  id uuid not null primary key default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  balance numeric(10, 2) not null default 0.00,
  unique(profile_id)
);
comment on table public.wallets is 'Stores the current balance for each user profile.';

-- 4. Ledger Table (Append-Only)
create table public.ledger (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  wallet_id uuid not null references public.wallets(id),
  amount numeric(10, 2) not null,
  transaction_type transaction_type not null,
  idempotency_key uuid not null,
  description text,
  metadata jsonb
);
comment on table public.ledger is 'Append-only audit trail of all transactions.';

-- Add a unique constraint for idempotency to prevent double entries.
alter table public.ledger add constraint ledger_idempotency_key_key unique (idempotency_key);

-- 5. Triage Sessions Table
create table public.triage_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  victim_id uuid not null references public.profiles(id),
  last_message text,
  risk_score float,
  escalated boolean not null default false,
  notes text
);
comment on table public.triage_sessions is 'Stores AI triage sessions that may need human intervention.';

-- 6. Indexes for performance
create index on public.wallets (profile_id);
create index on public.ledger (wallet_id);
create index on public.triage_sessions (victim_id);


-- 7. RLS Policies (Row Level Security) - Basic Setup
-- For a real project, these would be much more detailed.
alter table public.profiles enable row level security;
alter table public.wallets enable row level security;
alter table public.ledger enable row level security;
alter table public.triage_sessions enable row level security;

-- For this MVP, we will keep RLS simple and allow public read access for demonstration.
-- In production, you MUST define policies based on user roles and authentication.
create policy "Allow public read-only access" on public.profiles for select using (true);
create policy "Allow public read-only access" on public.wallets for select using (true);
create policy "Allow public read-only access" on public.ledger for select using (true);
create policy "Allow public read-only access" on public.triage_sessions for select using (true);

-- Allow admins to do anything. In a real app, this would check a JWT claim.
-- For now, we assume an admin role can be asserted somehow for server-side operations.
create policy "Allow admins full access" on public.profiles for all using (true);
create policy "Allow admins full access" on public.wallets for all using (true);
create policy "Allow admins full access" on public.ledger for all using (true);
create policy "Allow admins full access" on public.triage_sessions for all using (true);


-- 8. Stored Procedure for Purchases (RPC)
create or replace function public.process_aid_purchase(
  victim_profile_id uuid,
  merchant_profile_id uuid,
  purchase_amount numeric,
  idempotency_key uuid
)
returns text
language plpgsql
-- SECURITY DEFINER is used to execute the function with the privileges of the owner.
-- This is necessary to update tables that the calling user may not have direct access to.
-- Ensure the function owner has the necessary permissions.
as $$
declare
  victim_wallet_id uuid;
  merchant_wallet_id uuid;
  victim_current_balance numeric;
  transaction_description text;
  merchant_name text;
  victim_name text;
begin
  -- 1. Get wallet IDs for victim and merchant
  select id, (select full_name from public.profiles where id = victim_profile_id) into victim_wallet_id, victim_name from public.wallets where profile_id = victim_profile_id;
  select id, (select full_name from public.profiles where id = merchant_profile_id) into merchant_wallet_id, merchant_name from public.wallets where profile_id = merchant_profile_id;

  if victim_wallet_id is null then
    raise exception 'Victim wallet not found';
  end if;

  if merchant_wallet_id is null then
    raise exception 'Merchant wallet not found';
  end if;

  -- 2. Check victim's balance (within a transaction lock)
  select balance into victim_current_balance from public.wallets where id = victim_wallet_id for update;

  if victim_current_balance < purchase_amount then
    raise exception 'Insufficient funds';
  end if;

  -- 3. Insert debit for victim
  -- The unique constraint on idempotency_key will prevent duplicates and roll back the transaction.
  insert into public.ledger (wallet_id, amount, transaction_type, idempotency_key, description, metadata)
  values (victim_wallet_id, -purchase_amount, 'PURCHASE'::transaction_type, idempotency_key, 'Purchase at ' || merchant_name, jsonb_build_object('merchant_profile_id', merchant_profile_id));

  -- 4. Insert credit for merchant
  insert into public.ledger (wallet_id, amount, transaction_type, idempotency_key, description, metadata)
  values (merchant_wallet_id, purchase_amount, 'PURCHASE'::transaction_type, idempotency_key, 'Payment from ' || victim_name, jsonb_build_object('victim_profile_id', victim_profile_id));

  -- 5. Update balances
  update public.wallets set balance = balance - purchase_amount where id = victim_wallet_id;
  update public.wallets set balance = balance + purchase_amount where id = merchant_wallet_id;

  return 'Purchase successful';
end;
$$;


-- Function for disbursing aid
create or replace function public.disburse_aid(
  victim_profile_ids uuid[],
  disbursement_amount numeric,
  idempotency_key_prefix text
)
returns text
language plpgsql
as $$
declare
  victim_id uuid;
  victim_wallet_id uuid;
  generated_idempotency_key uuid;
begin
  if disbursement_amount <= 0 then
    raise exception 'Disbursement amount must be positive';
  end if;

  foreach victim_id in array victim_profile_ids
  loop
    select id into victim_wallet_id from public.wallets where profile_id = victim_id;

    if victim_wallet_id is not null then
      -- Generate a unique idempotency key for each victim to allow for partial retries if the whole batch fails
      generated_idempotency_key := gen_random_uuid();

      -- Use a sub-transaction block to handle potential duplicate idempotency keys gracefully
      begin
        -- Insert credit record
        insert into public.ledger (wallet_id, amount, transaction_type, idempotency_key, description, metadata)
        values (victim_wallet_id, disbursement_amount, 'AID_DISBURSEMENT'::transaction_type, generated_idempotency_key, 'Aid Disbursement', jsonb_build_object('batch_idempotency_prefix', idempotency_key_prefix));

        -- Update wallet balance
        update public.wallets set balance = balance + disbursement_amount where id = victim_wallet_id;
      exception
        when unique_violation then
          raise warning 'Idempotency key conflict for victim %, skipping disbursement.', victim_id;
      end;
    else
      raise warning 'Wallet for victim % not found, skipping disbursement.', victim_id;
    end if;
  end loop;

  return 'Disbursement process completed';
end;
$$;


-- Function to register a new victim and create a wallet
create or replace function public.register_victim(
  full_name text
)
returns uuid
language plpgsql
as $$
declare
  new_profile_id uuid;
begin
  -- Insert the new profile
  insert into public.profiles (full_name, role)
  values (full_name, 'victim')
  returning id into new_profile_id;

  -- Create a corresponding wallet
  insert into public.wallets (profile_id, balance)
  values (new_profile_id, 0);

  return new_profile_id;
end;
$$;
